version: '3'
services:
    db:
        image: mcr.microsoft.com/mssql/server:2019-latest
        volumes:
            - mssql:/var/opt/mssql
        logging:
            driver: none
        ports:
            - 1433:1433
        environment:
            ACCEPT_EULA: Y
            SA_PASSWORD: yourStrong(!)Password

    redis:
        image: redis:alpine
        ports:
            - 6379:6379

volumes:
    mssql:
